const routesConstants = Object.freeze({
  SCHEDULE_LIVE_CLASS: "/schedule-live-class",
  CREATE_LIVE_CLASS: "/create",
  GET_ALL_LIVE_CLASSES: "/get-all",
  GET_LIVE_CLASS_DETAILS: "/get-details",
  GET_UPCOMING_CLASS: "/get-upcoming-class",
  GENERIC_API: "/generic",
  GET_ALL_SUBJECTS: "/get-all-subjects",
  CREATE_FEEDBACK: "/create-feedback",
  LATEST_FEEDBACK: "/latest-feedback",
  LATEST_COMPLETEDCLASSROOM: "/latest-completed-live-classroom",
  TOPIC_FEEDBACK_RATING_DETAILS: "/topic-feedback-rating-details",
  UPLOAD_TIMETABLE: "/upload-timetable",
  GET_ALL_TIMETABLE: "/get-all-timetable",
  OPEN_FILE: "/open-file",
  IMAGE_TO_DOC: "/image-to-doc",
  UPLOAD_ASSIGNMENT_TO_CLASS_BY_ID: "/upload-assignment-to-class",

  SOLO: "/solo-lecture",
  SOLO_CLASSROOM: "/create-room",
  LATEST_CLASSROOM: "/latest-room",
  SOLO_CLASSROOM_RECORDINGS: "/solo-classroom-recording",
  SOLO_TOPIC_DETAILS_FILES_RECORDINGS: "/get-topic-details",
  SOLO_CLASSROOM_PRESIGNED_URL: "/generate-url",
  SOLOCLASSROOM_FILES: "/open-file/solo-files",
  SOLOCLASSROOM_DETAILS: "/get-details-data-for-class",
  GET_ALL_SOLOCLASSROOM: "/get-all-soloclassrooms",
  GET_SOLOCLASS_FOR_TOPICBASEDRECORDING:
    "/get-soloclass-for-topicbasedrecording",

  TOPIC_ASSIGNMENTS: "/assignment",
  CREATE_ASSIGNMENT: "/create",
  GET_ASSIGNMENT_TOPIC_ID: "/get-all-assignments-topic-id",
  DELETE_ASSIGNMENT: "/delete-assignment",
  LATEST_ASSIGNMENT: "/latest-assignment",
  RECENT_ONE_ASSIGNMENT: "/recent-assignment", // for student home page.
  ALL_ASSIGNMENT_WITH_FILES: "/all-assignment-with-files",
  UPLOAD_ASSIGNMENT: "/upload-assignments",
  GET_ASSIGNMENTS_BY_SUBJECTS: "/get-assignment-by-subject-id",
  GET_ASSIGNMENT_BY_TOPICID: "/get-assignment-by-topic-id",
  AUTH: "/auth",
  LOGIN: "/login",
  LOGIN_WITH_IP: "/login_with_ip",
  LOGIN_WITH_UNIQUE_ID: "/login_with_uid",
  RECORDING: "/recording",
  GET_SINGLE_RECORDING: "/get-single-recording",
  GET_RECORDING_BY_TOPIC_ONLY: "/get-recording-by-topic", // This is for INSP external website not for video portal at the moment
  UPDATE_RECORDING_DATA: "/update-recording-data",
  VIEW_RECORDING: "/view-recording",
  PLAY_RECORDING: "/play-recording",

  LECTURES_ENDPOINT: "/lecture",
  GET_ALL_LECTURE: "/get-all-lecture",
  GET_LECTURE_NO: "/get-lecture-no",
  GET_LECTURE_BY_TOPIC_NAME: "/get-lecture-by-topic-name/:topicId/:topicType",
  GET_LECTURE_BY_ID: "/get-lecture-by-id",

  UPDATE_SCHEDULE_CLASS: "/update-schedule-data",

  STUDENT_FEEDBACK: "/student-feedback",
  CREATE_STUDENT_FEEDBACK: "/create-student-feedback",
  GET_ALL_STUDENT_FEEDBACK: "/get-all-student-feedback",
  DELETE_STUDENT_FEEDBACK: "/delete-student-feedback/:id",
});

module.exports = routesConstants;
