const SOCKET_EVENTS = Object.freeze({
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  JOIN_ROOM_PREVIEW: "join_room_preview",
  JOIN_ROOM: "join_room",
  NEW_PEER_JOINED: "new_peer_joined",
  ROOM_UPDATE: "room_update",
  CREATE_WEB_RTC_TRANSPORT: "create_webrtc_transport",
  TRANSPORT_SEND_CONNECT: "transport_send_connect",
  TRANSPORT_RECV_CONNECT: "transport-recv-connect",
  TRANSPORT_PRODUCE: "transport_produce",
  NEW_PRODUCER: "new_producer",
  GET_PRODUCERS: "get_producers",
  CONSUME: "consume",
  CONSUMER_RESUME: "consumer-resume",
  DTLS_STATE_CHANGE: "dtlsstatechange",
  CLOSE: "close",
  TRANSPORT_CLOSE: "transportclose",
  PRODUCERCLOSE: "producerclose",
  PRODUCER_CLOSED: "producer-closed",
  CHAT_MSG_TO_SERVER: "chat_msg_to_server",
  CHAT_MSG_FROM_SERVER: "chat_msg_from_server",
  QUESTION_POSTED: "question_posted",
  QUESTION_SENT: "question_sent",
  PEER_LEAVED: "peer_leave",
  STOP_PRODUCING: "stop_producing",
  SOME_PRODUCER_CLOSED: "some_producer_closed",
  RAISE_HAND_TO_SERVER: "raise_hand_to_server",
  RAISE_HAND_FROM_SERVER: "raise_hand_from_server",
  UPLOAD_FILE_TO_SERVER: "upload_file_to_server",
  UPLOAD_FILE_FROM_SERVER: "upload_file_from_server",
  QUESTION_SENT_TO_SERVER: "question_sent_to_server",
  QUESTION_SENT_FROM_SERVER: "question_sent_from_server",
});

module.exports = SOCKET_EVENTS;
