stages:
  - build
  - test
  - deploy

# Define individual jobs within each stage.
# In this example, we'll create a simple build and test job, and a deploy job.

# Build stage
build:
  stage: build
  script:
    - echo "Building the application..."
  only:
    - dev

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."
    # You would typically run your actual test commands here.
    # For example: "npm test" for Node.js projects, "pytest" for Python, etc.
  only:
    - dev

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - dev
