stages:
  - deploy_dev

deploy_dev_job:
  stage: deploy_dev
  script:
    - echo "Starting Deploying to ..."
    - echo "${INSP_PEM_FILE}" > ssh_key.pem
    - chmod 400 ssh_key.pem
    - ssh -o StrictHostKeyChecking=no -i ssh_key.pem -A "${INSP_DEV_USER}"@"${INSP_DEV_SERVER_IP}" "cd /home/ubuntu/insp_dev_backend/inspbackend && git pull origin dev && npm run migrate && pm2 restart all"
  only:
    - dev
