const dotenv = require("dotenv");
dotenv.config({ path: "config/.env" });
const PORT = process.env.PORT;
const NODE_ENV = process.env.NODE_ENV;
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_REGION = process.env.AWS_REGION;
const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;
const INSP_EXTERNAL_WEBSITE_SECRET_KEY =
  process.env.INSP_EXTERNAL_WEBSITE_SECRET_KEY;
const ALLOWED_ORIGINS = process.env.ALLOWED_ORIGINS;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI;
const GOOGLE_REFRESH_TOKEN = process.env.GOOGLE_REFRESH_TOKEN;
const GOOGLE_GMAIL_USER = process.env.GOOGLE_GMAIL_USER;

module.exports = {
  PORT,
  NODE_ENV,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BUCKET_NAME,
  INSP_EXTERNAL_WEBSITE_SECRET_KEY,
  ALLOWED_ORIGINS,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  GOOGLE_REFRESH_TOKEN,
  GOOGLE_GMAIL_USER,
};
